<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKTZEnmb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKTZEnmb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKTZEnmb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKTZEnmb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKTZEnmb\App_KernelDevDebugContainer([
    'container.build_hash' => 'KTZEnmb',
    'container.build_id' => '8f8fe653',
    'container.build_time' => 1648800375,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKTZEnmb');
