<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ8ENrV1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ8ENrV1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ8ENrV1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ8ENrV1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ8ENrV1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q8ENrV1',
    'container.build_id' => 'b77fdf6b',
    'container.build_time' => 1649194916,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ8ENrV1');
