<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCdr9cwn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCdr9cwn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCdr9cwn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCdr9cwn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCdr9cwn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cdr9cwn',
    'container.build_id' => '3ff6e521',
    'container.build_time' => 1647813573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCdr9cwn');
