<?php

namespace ContainerFu10tuP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UAImIjOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uAImIjO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uAImIjO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PermissionController::addPost' => ['privates', '.service_locator.dKvJI5e', 'get_ServiceLocator_DKvJI5eService', true],
            'App\\Controller\\PermissionController::delete' => ['privates', '.service_locator.O.fYUTG', 'get_ServiceLocator_O_FYUTGService', true],
            'App\\Controller\\PermissionController::edit' => ['privates', '.service_locator.O.fYUTG', 'get_ServiceLocator_O_FYUTGService', true],
            'App\\Controller\\PermissionController::index' => ['privates', '.service_locator.hsnnqmr', 'get_ServiceLocator_HsnnqmrService', true],
            'App\\Controller\\PermissionController::show' => ['privates', '.service_locator.vy4R6N6', 'get_ServiceLocator_Vy4R6N6Service', true],
            'App\\Controller\\ProfilController::delete' => ['privates', '.service_locator.0_4O5OK', 'get_ServiceLocator_04O5OKService', true],
            'App\\Controller\\ProfilController::edit' => ['privates', '.service_locator.0_4O5OK', 'get_ServiceLocator_04O5OKService', true],
            'App\\Controller\\ProfilController::index' => ['privates', '.service_locator.8mWyt.U', 'get_ServiceLocator_8mWyt_UService', true],
            'App\\Controller\\ProfilController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProfilController::show' => ['privates', '.service_locator.8mWyt.U', 'get_ServiceLocator_8mWyt_UService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.aY7OgVe', 'get_ServiceLocator_AY7OgVeService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.aY7OgVe', 'get_ServiceLocator_AY7OgVeService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.lwhU4dN', 'get_ServiceLocator_LwhU4dNService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\PermissionController:addPost' => ['privates', '.service_locator.dKvJI5e', 'get_ServiceLocator_DKvJI5eService', true],
            'App\\Controller\\PermissionController:delete' => ['privates', '.service_locator.O.fYUTG', 'get_ServiceLocator_O_FYUTGService', true],
            'App\\Controller\\PermissionController:edit' => ['privates', '.service_locator.O.fYUTG', 'get_ServiceLocator_O_FYUTGService', true],
            'App\\Controller\\PermissionController:index' => ['privates', '.service_locator.hsnnqmr', 'get_ServiceLocator_HsnnqmrService', true],
            'App\\Controller\\PermissionController:show' => ['privates', '.service_locator.vy4R6N6', 'get_ServiceLocator_Vy4R6N6Service', true],
            'App\\Controller\\ProfilController:delete' => ['privates', '.service_locator.0_4O5OK', 'get_ServiceLocator_04O5OKService', true],
            'App\\Controller\\ProfilController:edit' => ['privates', '.service_locator.0_4O5OK', 'get_ServiceLocator_04O5OKService', true],
            'App\\Controller\\ProfilController:index' => ['privates', '.service_locator.8mWyt.U', 'get_ServiceLocator_8mWyt_UService', true],
            'App\\Controller\\ProfilController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProfilController:show' => ['privates', '.service_locator.8mWyt.U', 'get_ServiceLocator_8mWyt_UService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.aY7OgVe', 'get_ServiceLocator_AY7OgVeService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.aY7OgVe', 'get_ServiceLocator_AY7OgVeService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.lwhU4dN', 'get_ServiceLocator_LwhU4dNService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\PermissionController::addPost' => '?',
            'App\\Controller\\PermissionController::delete' => '?',
            'App\\Controller\\PermissionController::edit' => '?',
            'App\\Controller\\PermissionController::index' => '?',
            'App\\Controller\\PermissionController::show' => '?',
            'App\\Controller\\ProfilController::delete' => '?',
            'App\\Controller\\ProfilController::edit' => '?',
            'App\\Controller\\ProfilController::index' => '?',
            'App\\Controller\\ProfilController::new' => '?',
            'App\\Controller\\ProfilController::show' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PermissionController:addPost' => '?',
            'App\\Controller\\PermissionController:delete' => '?',
            'App\\Controller\\PermissionController:edit' => '?',
            'App\\Controller\\PermissionController:index' => '?',
            'App\\Controller\\PermissionController:show' => '?',
            'App\\Controller\\ProfilController:delete' => '?',
            'App\\Controller\\ProfilController:edit' => '?',
            'App\\Controller\\ProfilController:index' => '?',
            'App\\Controller\\ProfilController:new' => '?',
            'App\\Controller\\ProfilController:show' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
