<?php

namespace ContainerFu10tuP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HsnnqmrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hsnnqmr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hsnnqmr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'permissionRepository' => ['privates', 'App\\Repository\\PermissionRepository', 'getPermissionRepositoryService', true],
        ], [
            'permissionRepository' => 'App\\Repository\\PermissionRepository',
        ]);
    }
}
