<?php

namespace ContainerCdr9cwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EbhKswkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ebhKswk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ebhKswk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'profilRepository' => ['privates', '.errored.is_zF9g', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::new()": the $profilRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ProfilRepository". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'profilRepository' => '?',
        ]);
    }
}
