<?php

namespace ContainerCdr9cwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_IsZF9gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.is_zF9g' shared service.
     *
     * @return \App\Controller\ProfilRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\UserController::new()": the $profilRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ProfilRepository". Did you forget to add a use statement?');
    }
}
