<?php

namespace ContainerCAxSgBT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T0Rq_QUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t0Rq.qU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t0Rq.qU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProfilController::delete' => ['privates', '.service_locator.1UrvX8b', 'get_ServiceLocator_1UrvX8bService', true],
            'App\\Controller\\ProfilController::edit' => ['privates', '.service_locator.1UrvX8b', 'get_ServiceLocator_1UrvX8bService', true],
            'App\\Controller\\ProfilController::index' => ['privates', '.service_locator.SDxDLzt', 'get_ServiceLocator_SDxDLztService', true],
            'App\\Controller\\ProfilController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\ProfilController::show' => ['privates', '.service_locator.SDxDLzt', 'get_ServiceLocator_SDxDLztService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ProfilController:delete' => ['privates', '.service_locator.1UrvX8b', 'get_ServiceLocator_1UrvX8bService', true],
            'App\\Controller\\ProfilController:edit' => ['privates', '.service_locator.1UrvX8b', 'get_ServiceLocator_1UrvX8bService', true],
            'App\\Controller\\ProfilController:index' => ['privates', '.service_locator.SDxDLzt', 'get_ServiceLocator_SDxDLztService', true],
            'App\\Controller\\ProfilController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\ProfilController:show' => ['privates', '.service_locator.SDxDLzt', 'get_ServiceLocator_SDxDLztService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ProfilController::delete' => '?',
            'App\\Controller\\ProfilController::edit' => '?',
            'App\\Controller\\ProfilController::index' => '?',
            'App\\Controller\\ProfilController::new' => '?',
            'App\\Controller\\ProfilController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProfilController:delete' => '?',
            'App\\Controller\\ProfilController:edit' => '?',
            'App\\Controller\\ProfilController:index' => '?',
            'App\\Controller\\ProfilController:new' => '?',
            'App\\Controller\\ProfilController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
