<?php

namespace ContainerKTZEnmb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O_FYUTGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O.fYUTG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O.fYUTG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PermissionRepository' => ['privates', 'App\\Repository\\PermissionRepository', 'getPermissionRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'PermissionRepository' => 'App\\Repository\\PermissionRepository',
            'entityManager' => '?',
        ]);
    }
}
