<?php

namespace ContainerKTZEnmb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vy4R6N6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vy4R6N6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vy4R6N6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PermissionRepository' => ['privates', 'App\\Repository\\PermissionRepository', 'getPermissionRepositoryService', true],
        ], [
            'PermissionRepository' => 'App\\Repository\\PermissionRepository',
        ]);
    }
}
